baseURL = 'https://0xznx.com/'
languageCode = 'en-us'
title = 'znx // David Alves'

[params]
   favicon_32 = "/avatar.png"
   favicon_16 = "/avatar.png"
[menu]

  [[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "0xDump"
    url = "/dump/"
    weight = 2

  [[menu.main]]
    name = "Objectives"
    url = "/objectives/"
    weight = 3

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4
